services:

  db:
    image: mariadb:10.6-focal
    
    container_name: db

    restart: always

    environment:
      - MARIADB_ROOT_PASSWORD=1234
    
    volumes:
      - ./bdd:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=supersecretkey
    depends_on:
      db:
        condition: service_healthy
    

  #frontend:
  #  build: ./frontend
  #  ports:
  #    - "8080:80"
  #  container_name: frontend