services:

  db:
    image: mariadb:10.6-focal
    container_name: ${DB_CONTAINER}
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_CONTAINER=${DB_CONTAINER}
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
